### ISSUE TITLE
Note that it works only with react-markdown 5

### ISSUE THREAD

**Issue by 1player** [rjantoine/react-markdown-remark-directive#1]
Fine if that's the case, but should probably make a note of it in the README. 

It's taken me 30 minutes to figure out why I couldn't make it work, then I saw that react-markdown has recently been upgraded to major version 6 breaking many plugins, including this one.

**Comment by rjantoine** [comment]
Thank you, I will try and find time to revisit this project shortly in light of the react-markdown 5 update.

**Comment by rjantoine** [comment]
Please see the following working example for the new version 6.

https://codesandbox.io/s/interesting-matsumoto-y6x6n?file=/src/App.js
