### ISSUE TITLE
Small typo in README

### ISSUE THREAD

**Issue by 1player** [rjantoine/react-markdown-remark-directive#2]
In the first code snippet `rmDirective.plugin` should actually be `rmDirective`, as the plugin function is now the default export.

So instead of:

```javascript
import rmDirective from 'react-markdown-remark-directive'

const rmPlugins = [
    [rmDirective.plugin, {components}],
]
```

One would use:

```javascript
import rmDirective from 'react-markdown-remark-directive'

const rmPlugins = [
    [rmDirective, {components}],
]
```

**Comment by rjantoine** [comment]
Good catch, I had refactored my code but must have forgotten to change it in the snippet. Thanks.
